use std::sync::Arc;
use tray_icon::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use windows::Win32::UI::WindowsAndMessaging::{GetSystemMetrics, SM_CXSMICON};

use crate::config::WheelMode;
use crate::hook::SharedState;
use crate::theme;

/// Manages the system tray icon. The context menu is rendered as a GPUI
/// popup window (see `gui::show_tray_menu`), so the tray icon itself is
/// icon-only: no native menu is attached. Left-click opens settings,
/// right-click opens the GPUI context menu.
pub struct Tray {
    _tray: TrayIcon,
}

impl Tray {
    /// Create the tray icon (no native menu).
    /// `shared` is used to read the current wheel-mode for the icon color.
    pub fn new(shared: &Arc<SharedState>) -> Result<Self, String> {
        // Create the tray icon (color reflects the current wheel mode).
        let icon = create_tray_icon(shared.wheel_mode());

        let tray = TrayIconBuilder::new()
            // No native menu; right-click is handled by the GPUI popup.
            .with_menu_on_left_click(false)
            .with_tooltip("Sabitori")
            .with_icon(icon)
            .build()
            .map_err(|e| format!("Failed to create tray icon: {e}"))?;

        Ok(Self {
            _tray: tray,
        })
    }

    /// Clones the tray icon handle so callers can update the tooltip after
    /// the `Tray` has been handed off for the lifetime of the app.
    #[allow(clippy::used_underscore_binding)]
    pub fn icon(&self) -> TrayIcon {
        self._tray.clone()
    }
}

/// Generate a tray icon whose color scheme reflects the given wheel mode.
/// Call with `tray_icon.set_icon(Some(icon))` to update the icon when the
/// mode changes.
pub fn icon_for_mode(mode: WheelMode) -> tray_icon::Icon {
    create_tray_icon(mode)
}

// Multi-resolution .ico files generated by `build.rs` from the Tabler
// `mouse` (on) and `mouse-off` (off) SVGs. Each file contains 16/20/24/32/48
// px images and a light (white) and dark (near-black) variant.
const TRAY_LIGHT_ON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-light-on.ico"));
const TRAY_LIGHT_OFF: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-light-off.ico"));
const TRAY_DARK_ON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-dark-on.ico"));
const TRAY_DARK_OFF: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-dark-off.ico"));

/// Actions the tray menu can trigger.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayAction {
    Settings,
    Quit,
    /// Show the GPUI-rendered context menu at the cursor.
    ShowMenu,
}

/// A shared slot for actions emitted by the GPUI tray menu (which runs
/// in a separate window and can't use the native MenuEvent channel).
/// Only one action is ever pending at a time (the menu closes on click),
/// so a single atomic is sufficient.
static PENDING_MENU_ACTION: std::sync::OnceLock<std::sync::Mutex<Option<TrayAction>>> =
    std::sync::OnceLock::new();

fn pending_action_slot() -> &'static std::sync::Mutex<Option<TrayAction>> {
    PENDING_MENU_ACTION.get_or_init(|| std::sync::Mutex::new(None))
}

/// Called from the GPUI tray menu's click handler to queue an action.
pub fn poll_menu_action(action: TrayAction) {
    if let Ok(mut slot) = pending_action_slot().lock() {
        *slot = Some(action);
    }
}

/// Drain a pending GPUI tray menu action, if any.
pub fn take_menu_action() -> Option<TrayAction> {
    if let Ok(mut slot) = pending_action_slot().lock() {
        return slot.take();
    }
    None
}

/// Poll for tray icon mouse events. A left-click opens the settings
/// window; a right-click opens the GPUI-rendered context menu (instead
/// of the native menu, which is not attached to the tray icon).
///
/// The Windows-only `DoubleClick` event is deliberately ignored, it
/// arrives after the two single-click events that already covered it.
pub fn poll_tray_click() -> Option<TrayAction> {
    let receiver = TrayIconEvent::receiver();
    let mut action = None;
    // Drain the whole queue so a burst (e.g. a double-click) doesn't leave
    // stale events to be processed on a later poll.
    while let Ok(event) = receiver.try_recv() {
        if let TrayIconEvent::Click {
            button,
            button_state: MouseButtonState::Up,
            ..
        } = event
        {
            match button {
                MouseButton::Left => action = Some(TrayAction::Settings),
                MouseButton::Right => action = Some(TrayAction::ShowMenu),
                _ => {}
            }
        }
    }
    action
}

/// Create a tray icon from the generated multi-resolution .ico.
///
/// The .ico contains Tabler `mouse` (on) and `mouse-off` (off) images at
/// 16/20/24/32/48 px. The color is chosen to contrast with the taskbar:
/// a white stroke on a dark taskbar and a near-black stroke on a light
/// taskbar. Windows will pick the closest resolution to the tray's current
/// DPI.
fn create_tray_icon(mode: WheelMode) -> tray_icon::Icon {
    // Pick the icon color that contrasts with the taskbar:
    // white mouse on a dark taskbar, dark mouse on a light taskbar.
    let icon_theme = if theme::is_light_mode() { "dark" } else { "light" };
    let state = if mode == WheelMode::DirectionLock { "on" } else { "off" };
    let bytes = match (icon_theme, state) {
        ("light", "on") => TRAY_LIGHT_ON,
        ("light", "off") => TRAY_LIGHT_OFF,
        ("dark", "on") => TRAY_DARK_ON,
        ("dark", "off") => TRAY_DARK_OFF,
        _ => TRAY_DARK_OFF,
    };

    let temp = std::env::temp_dir().join(format!("sabitori-tray-{}-{}.ico", icon_theme, state));
    std::fs::write(&temp, bytes).expect("failed to write temporary tray ico");

    // Ask Windows for the small icon size at the current DPI so the ICO
    // image nearest to the tray display size is selected.
    let size = unsafe { GetSystemMetrics(SM_CXSMICON) };
    let requested = if size > 0 {
        Some((size as u32, size as u32))
    } else {
        None
    };

    let icon = tray_icon::Icon::from_path(&temp, requested).unwrap_or_else(|_| {
        // Worst-case fallback: a 1x1 white pixel so the tray icon still
        // has something to display.
        tray_icon::Icon::from_rgba(vec![255, 255, 255, 255], 1, 1)
            .expect("1x1 icon should always work")
    });

    // The .ico has already been loaded into an HICON, so the temp file can go.
    std::fs::remove_file(&temp).ok();

    icon
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn icon_has_visible_pixels() {
        // The rendered SVG should produce a non-empty 64×64 icon for both
        // wheel modes (and not fall back to the 1×1 pixel).
        let _ = create_tray_icon(WheelMode::DirectionLock);
        let _ = create_tray_icon(WheelMode::Off);
    }

    #[test]
    fn menu_action_roundtrip() {
        // poll_menu_action -> take_menu_action should deliver the action.
        poll_menu_action(TrayAction::Settings);
        assert_eq!(take_menu_action(), Some(TrayAction::Settings));
        assert_eq!(take_menu_action(), None);

        poll_menu_action(TrayAction::Quit);
        assert_eq!(take_menu_action(), Some(TrayAction::Quit));
        assert_eq!(take_menu_action(), None);
    }
}
