use std::sync::Arc;
use tray_icon::menu::{Menu, MenuEvent, MenuId, MenuItem};
use tray_icon::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use windows::Win32::UI::WindowsAndMessaging::{GetSystemMetrics, SM_CXSMICON};

use crate::config::WheelMode;
use crate::hook::SharedState;
use crate::theme;

/// Menu IDs for identifying which item was clicked.
const ID_SETTINGS: &str = "settings";
const ID_QUIT: &str = "quit";

/// Manages the system tray icon and its menu. Deliberately minimal: just
/// Settings and Quit. Mode toggling lives in the settings window.
pub struct Tray {
    _tray: TrayIcon,
    /// Keep menu items alive, they're referenced by the tray internally.
    _menu: Menu,
}

impl Tray {
    /// Create the tray icon and menu.
    /// `shared` is used to read the current wheel-mode for the icon color.
    pub fn new(shared: &Arc<SharedState>) -> Result<Self, String> {
        let menu = Menu::new();

        let settings_item = MenuItem::with_id(ID_SETTINGS, "Settings", true, None);
        let quit_item = MenuItem::with_id(ID_QUIT, "Quit", true, None);

        menu.append(&settings_item)
            .map_err(|e| format!("Failed to append settings: {e}"))?;
        menu.append(&quit_item)
            .map_err(|e| format!("Failed to append quit: {e}"))?;

        // Create the tray icon (color reflects the current wheel mode).
        let icon = create_tray_icon(shared.wheel_mode());

        let tray = TrayIconBuilder::new()
            .with_menu(Box::new(menu.clone()))
            // Left-click is reserved for opening the settings window, so the
            // context menu must only appear on right-click. tray_icon
            // defaults to showing the menu on left-click too, which popped
            // the menu on any left click (and could even do so at launch).
            .with_menu_on_left_click(false)
            .with_tooltip("Sabitori")
            .with_icon(icon)
            .build()
            .map_err(|e| format!("Failed to create tray icon: {e}"))?;

        Ok(Self {
            _tray: tray,
            _menu: menu,
        })
    }

    /// Clones the tray icon handle so callers can update the tooltip after
    /// the `Tray` has been handed off for the lifetime of the app.
    #[allow(clippy::used_underscore_binding)]
    pub fn icon(&self) -> TrayIcon {
        self._tray.clone()
    }
}

/// Generate a tray icon whose color scheme reflects the given wheel mode.
/// Call with `tray_icon.set_icon(Some(icon))` to update the icon when the
/// mode changes.
pub fn icon_for_mode(mode: WheelMode) -> tray_icon::Icon {
    create_tray_icon(mode)
}

// Multi-resolution .ico files generated by `build.rs` from the Tabler
// `mouse` (on) and `mouse-off` (off) SVGs. Each file contains 16/20/24/32/48
// px images and a light (white) and dark (near-black) variant.
const TRAY_LIGHT_ON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-light-on.ico"));
const TRAY_LIGHT_OFF: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-light-off.ico"));
const TRAY_DARK_ON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-dark-on.ico"));
const TRAY_DARK_OFF: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-dark-off.ico"));

/// Actions the tray menu can trigger.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayAction {
    Settings,
    Quit,
}

/// Poll for tray menu events and map them to actions.
/// Call this from the main/GPUI thread's event handling.
pub fn poll_menu_event() -> Option<TrayAction> {
    // MenuEvent::receiver() is a crossbeam channel receiver.
    // We try_recv to check for events without blocking.
    let receiver = MenuEvent::receiver();
    match receiver.try_recv() {
        Ok(event) => map_menu_event(&event.id),
        Err(_) => None,
    }
}

fn map_menu_event(id: &MenuId) -> Option<TrayAction> {
    match id.0.as_str() {
        ID_SETTINGS => Some(TrayAction::Settings),
        ID_QUIT => Some(TrayAction::Quit),
        _ => None,
    }
}

/// Poll for tray icon mouse events and map a left-click to the Settings
/// action, so a single M1 click on the tray icon opens the settings window.
///
/// The context menu itself is shown automatically by the tray on right-click;
/// left-clicks reach us through this separate event channel. The Windows-only
/// `DoubleClick` event is deliberately ignored, it arrives after the two
/// single-click events that already covered it.
pub fn poll_tray_click() -> Option<TrayAction> {
    let receiver = TrayIconEvent::receiver();
    let mut action = None;
    // Drain the whole queue so a burst (e.g. a double-click) doesn't leave
    // stale events to be processed on a later poll.
    while let Ok(event) = receiver.try_recv() {
        if let TrayIconEvent::Click {
            button: MouseButton::Left,
            button_state: MouseButtonState::Up,
            ..
        } = event
        {
            action = Some(TrayAction::Settings);
        }
    }
    action
}

/// Create a tray icon from the generated multi-resolution .ico.
///
/// The .ico contains Tabler `mouse` (on) and `mouse-off` (off) images at
/// 16/20/24/32/48 px. The color is chosen to contrast with the taskbar:
/// a white stroke on a dark taskbar and a near-black stroke on a light
/// taskbar. Windows will pick the closest resolution to the tray's current
/// DPI.
fn create_tray_icon(mode: WheelMode) -> tray_icon::Icon {
    // Pick the icon color that contrasts with the taskbar:
    // white mouse on a dark taskbar, dark mouse on a light taskbar.
    let icon_theme = if theme::is_light_mode() { "dark" } else { "light" };
    let state = if mode == WheelMode::DirectionLock { "on" } else { "off" };
    let bytes = match (icon_theme, state) {
        ("light", "on") => TRAY_LIGHT_ON,
        ("light", "off") => TRAY_LIGHT_OFF,
        ("dark", "on") => TRAY_DARK_ON,
        ("dark", "off") => TRAY_DARK_OFF,
        _ => TRAY_DARK_OFF,
    };

    let temp = std::env::temp_dir().join(format!("sabitori-tray-{}-{}.ico", icon_theme, state));
    std::fs::write(&temp, bytes).expect("failed to write temporary tray ico");

    // Ask Windows for the small icon size at the current DPI so the ICO
    // image nearest to the tray display size is selected.
    let size = unsafe { GetSystemMetrics(SM_CXSMICON) };
    let requested = if size > 0 {
        Some((size as u32, size as u32))
    } else {
        None
    };

    let icon = tray_icon::Icon::from_path(&temp, requested).unwrap_or_else(|_| {
        // Worst-case fallback: a 1x1 white pixel so the tray icon still
        // has something to display.
        tray_icon::Icon::from_rgba(vec![255, 255, 255, 255], 1, 1)
            .expect("1x1 icon should always work")
    });

    // The .ico has already been loaded into an HICON, so the temp file can go.
    std::fs::remove_file(&temp).ok();

    icon
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn icon_has_visible_pixels() {
        // The rendered SVG should produce a non-empty 64×64 icon for both
        // wheel modes (and not fall back to the 1×1 pixel).
        let _ = create_tray_icon(WheelMode::DirectionLock);
        let _ = create_tray_icon(WheelMode::Off);
    }

    #[test]
    fn map_menu_event_known_ids() {
        assert_eq!(
            map_menu_event(&MenuId::new(ID_SETTINGS)),
            Some(TrayAction::Settings)
        );
        assert_eq!(
            map_menu_event(&MenuId::new(ID_QUIT)),
            Some(TrayAction::Quit)
        );
    }

    #[test]
    fn map_menu_event_unknown_id_returns_none() {
        assert_eq!(
            map_menu_event(&MenuId::new("nonexistent")),
            None
        );
    }
}
